export const MT = [
    'Acorizal',
    'Água Boa',
    'Alta Floresta',
    'Alto Araguaia',
    'Alto Boa Vista',
    'Alto Garças',
    'Alto Paraguai',
    'Alto Taquari',
    'Apiacás',
    'Araguaiana',
    'Araguainha',
    'Araputanga',
    'Arenápolis',
    'Aripuanã',
    'Barão de Melgaço',
    'Barra do Bugres',
    'Barra do Garças',
    'Bom Jesus do Araguaia',
    'Brasnorte',
    'Cáceres',
    'Campinápolis',
    'Campo Novo do Parecis',
    'Campo Verde',
    'Campos de Júlio',
    'Canabrava do Norte',
    'Canarana',
    'Carlinda',
    'Castanheira',
    'Chapada Dos Guimarães',
    'Cláudia',
    'Cocalinho',
    'Colíder',
    'Colniza',
    'Comodoro',
    'Confresa',
    'Conquista D´oeste',
    'Cotriguaçu',
    'Cuiabá',
    'Curvelândia',
    'Denise',
    'Diamantino',
    'Dom Aquino',
    'Feliz Natal',
    'Figueirópolis D´oeste',
    'Gaúcha do Norte',
    'General Carneiro',
    'Glória D´oeste',
    'Guarantã do Norte',
    'Guiratinga',
    'Indiavaí',
    'Ipiranga do Norte',
    'Itanhangá',
    'Itaúba',
    'Itiquira',
    'Jaciara',
    'Jangada',
    'Jauru',
    'Juara',
    'Juína',
    'Juruena',
    'Juscimeira',
    'Lambari D´oeste',
    'Lucas do Rio Verde',
    'Luciára',
    'Vila Bela da Santíssima Trindade',
    'Marcelândia',
    'Matupá',
    'Mirassol D´oeste',
    'Nobres',
    'Nortelândia',
    'Nossa Senhora do Livramento',
    'Nova Bandeirantes',
    'Nova Nazaré',
    'Nova Lacerda',
    'Nova Santa Helena',
    'Nova Brasilândia',
    'Nova Canaã do Norte',
    'Nova Mutum',
    'Nova Olímpia',
    'Nova Ubiratã',
    'Nova Xavantina',
    'Novo Mundo',
    'Novo Horizonte do Norte',
    'Novo São Joaquim',
    'Paranaíta',
    'Paranatinga',
    'Novo Santo Antônio',
    'Pedra Preta',
    'Peixoto de Azevedo',
    'Planalto da Serra',
    'Poconé',
    'Pontal do Araguaia',
    'Ponte Branca',
    'Pontes e Lacerda',
    'Porto Alegre do Norte',
    'Porto Dos Gaúchos',
    'Porto Esperidião',
    'Porto Estrela',
    'Poxoréo',
    'Primavera do Leste',
    'Querência',
    'São José Dos Quatro Marcos',
    'Reserva do Cabaçal',
    'Ribeirão Cascalheira',
    'Ribeirãozinho',
    'Rio Branco',
    'Santa Carmem',
    'Santo Afonso',
    'São José do Povo',
    'São José do Rio Claro',
    'São José do Xingu',
    'São Pedro da Cipa',
    'Rondolândia',
    'Rondonópolis',
    'Rosário Oeste',
    'Santa Cruz do Xingu',
    'Salto do Céu',
    'Santa Rita do Trivelato',
    'Santa Terezinha',
    'Santo Antônio do Leste',
    'Santo Antônio do Leverger',
    'São Félix do Araguaia',
    'Sapezal',
    'Serra Nova Dourada',
    'Sinop',
    'Sorriso',
    'Tabaporã',
    'Tangará da Serra',
    'Tapurah',
    'Terra Nova do Norte',
    'Tesouro',
    'Torixoréu',
    'União do Sul',
    'Vale de São Domingos',
    'Várzea Grande',
    'Vera',
    'Vila Rica',
    'Nova Guarita',
    'Nova Marilândia',
    'Nova Maringá',
    'Nova Monte Verde',
]
