export const RO = [
    'Alta Floresta D´oeste',
    'Ariquemes',
    'Cabixi',
    'Cacoal',
    'Cerejeiras',
    'Colorado do Oeste',
    'Corumbiara',
    'Costa Marques',
    'Espigão D´oeste',
    'Guajará-mirim',
    'Jaru',
    'Ji-paraná',
    'Machadinho D´oeste',
    'Nova Brasilândia D´oeste',
    'Ouro Preto do Oeste',
    'Pimenta Bueno',
    'Porto Velho',
    'Presidente Médici',
    'Rio Crespo',
    'Rolim de Moura',
    'Santa Luzia D´oeste',
    'Vilhena',
    'São Miguel do Guaporé',
    'Nova Mamoré',
    'Alvorada D´oeste',
    'Alto Alegre Dos Parecis',
    'Alto Paraíso',
    'Buritis',
    'Novo Horizonte do Oeste',
    'Cacaulândia',
    'Campo Novo de Rondônia',
    'Candeias do Jamari',
    'Castanheiras',
    'Chupinguaia',
    'Cujubim',
    'Governador Jorge Teixeira',
    'Itapuã do Oeste',
    'Ministro Andreazza',
    'Mirante da Serra',
    'Monte Negro',
    'Nova União',
    'Parecis',
    'Pimenteiras do Oeste',
    'Primavera de Rondônia',
    'São Felipe D´oeste',
    'São Francisco do Guaporé',
    'Seringueiras',
    'Teixeirópolis',
    'Theobroma',
    'Urupá',
    'Vale do Anari',
    'Vale do Paraíso',
]
